SECTION "NPC Sprites 1", ROMX

ScientistSprite::        INCBIN "gfx/sprites/scientist.2bpp"
RockerSprite::           INCBIN "gfx/sprites/rocker.2bpp"
SwimmerSprite::          INCBIN "gfx/sprites/swimmer.2bpp"
SafariZoneWorkerSprite:: INCBIN "gfx/sprites/safari_zone_worker.2bpp"
GymGuideSprite::         INCBIN "gfx/sprites/gym_guide.2bpp"
GrampsSprite::           INCBIN "gfx/sprites/gramps.2bpp"
ClerkSprite::            INCBIN "gfx/sprites/clerk.2bpp"
FishingGuruSprite::      INCBIN "gfx/sprites/fishing_guru.2bpp"
GrannySprite::           INCBIN "gfx/sprites/granny.2bpp"
NurseSprite::            INCBIN "gfx/sprites/nurse.2bpp"
LinkReceptionistSprite:: INCBIN "gfx/sprites/link_receptionist.2bpp"
SilphPresidentSprite::   INCBIN "gfx/sprites/silph_president.2bpp"
SilphWorkerMSprite::     INCBIN "gfx/sprites/silph_worker_m.2bpp"
WardenSprite::           INCBIN "gfx/sprites/warden.2bpp"
CaptainSprite::          INCBIN "gfx/sprites/captain.2bpp"
FisherSprite::           INCBIN "gfx/sprites/fisher.2bpp"
KogaSprite::             INCBIN "gfx/sprites/koga.2bpp"
GuardSprite::            INCBIN "gfx/sprites/guard.2bpp"
PokeBallSprite::         INCBIN "gfx/sprites/poke_ball.2bpp"
FossilSprite::           INCBIN "gfx/sprites/fossil.2bpp"
BoulderSprite::          INCBIN "gfx/sprites/boulder.2bpp"
PaperSprite::            INCBIN "gfx/sprites/paper.2bpp"
PokedexSprite::          INCBIN "gfx/sprites/pokedex.2bpp"
ClipboardSprite::        INCBIN "gfx/sprites/clipboard.2bpp"
SnorlaxSprite::          INCBIN "gfx/sprites/snorlax.2bpp"
OldAmberSprite::         INCBIN "gfx/sprites/old_amber.2bpp"
GamblerAsleepSprite::    INCBIN "gfx/sprites/gambler_asleep.2bpp"
QuestionMarkSprite::     INCBIN "gfx/sprites/question_mark.2bpp"
LittleBoySprite::        INCBIN "gfx/sprites/little_boy.2bpp"
DoduoSprite::            INCBIN "gfx/sprites/doduo.2bpp"


SECTION "NPC Sprites 2", ROMX

RedBikeSprite::          INCBIN "gfx/sprites/red_bike.2bpp"
RedSprite::              INCBIN "gfx/sprites/red.2bpp"
GreenBikeSprite::        INCBIN "gfx/sprites/green_bike.2bpp"
GreenSprite::            INCBIN "gfx/sprites/green.2bpp"
BlueSprite::             INCBIN "gfx/sprites/blue.2bpp"
OakSprite::              INCBIN "gfx/sprites/oak.2bpp"
YoungsterSprite::        INCBIN "gfx/sprites/youngster.2bpp"
MonsterSprite::          INCBIN "gfx/sprites/monster.2bpp"
CooltrainerFSprite::     INCBIN "gfx/sprites/cooltrainer_f.2bpp"
CooltrainerMSprite::     INCBIN "gfx/sprites/cooltrainer_m.2bpp"
LittleGirlSprite::       INCBIN "gfx/sprites/little_girl.2bpp"
BirdSprite::             INCBIN "gfx/sprites/bird.2bpp"
MiddleAgedManSprite::    INCBIN "gfx/sprites/middle_aged_man.2bpp"
GamblerSprite::          INCBIN "gfx/sprites/gambler.2bpp"
SuperNerdSprite::        INCBIN "gfx/sprites/super_nerd.2bpp"
GirlSprite::             INCBIN "gfx/sprites/girl.2bpp"
HikerSprite::            INCBIN "gfx/sprites/hiker.2bpp"
BeautySprite::           INCBIN "gfx/sprites/beauty.2bpp"
GentlemanSprite::        INCBIN "gfx/sprites/gentleman.2bpp"
DaisySprite::            INCBIN "gfx/sprites/daisy.2bpp"
BikerSprite::            INCBIN "gfx/sprites/biker.2bpp"
SailorSprite::           INCBIN "gfx/sprites/sailor.2bpp"
CookSprite::             INCBIN "gfx/sprites/cook.2bpp"
BikeShopClerkSprite::    INCBIN "gfx/sprites/bike_shop_clerk.2bpp"
MrFujiSprite::           INCBIN "gfx/sprites/mr_fuji.2bpp"
GiovanniSprite::         INCBIN "gfx/sprites/giovanni.2bpp"
RocketSprite::           INCBIN "gfx/sprites/rocket.2bpp"
ChannelerSprite::        INCBIN "gfx/sprites/channeler.2bpp"
WaiterSprite::           INCBIN "gfx/sprites/waiter.2bpp"
SilphWorkerFSprite::     INCBIN "gfx/sprites/silph_worker_f.2bpp"
MiddleAgedWomanSprite::  INCBIN "gfx/sprites/middle_aged_woman.2bpp"
BrunetteGirlSprite::     INCBIN "gfx/sprites/brunette_girl.2bpp"
LanceSprite::            INCBIN "gfx/sprites/lance.2bpp"
MomSprite::              INCBIN "gfx/sprites/mom.2bpp"
GameboyKidSprite::       INCBIN "gfx/sprites/gameboy_kid.2bpp"
FairySprite::            INCBIN "gfx/sprites/fairy.2bpp"
AgathaSprite::           INCBIN "gfx/sprites/agatha.2bpp"
BrunoSprite::            INCBIN "gfx/sprites/bruno.2bpp"
LoreleiSprite::          INCBIN "gfx/sprites/lorelei.2bpp"
SeelSprite::             INCBIN "gfx/sprites/seel.2bpp"


SECTION "NPC Sprites 3", ROMX

OfficerJennySprite::     INCBIN "gfx/sprites/officer_jenny.2bpp"
PikachuSprite::          INCBIN "gfx/sprites/pikachu.2bpp"
SandshrewSprite::        INCBIN "gfx/sprites/sandshrew.2bpp"
OddishSprite::           INCBIN "gfx/sprites/oddish.2bpp"
BulbasaurSprite::        INCBIN "gfx/sprites/bulbasaur.2bpp"
JigglypuffSprite::       INCBIN "gfx/sprites/jigglypuff.2bpp"
ClefairySprite::         INCBIN "gfx/sprites/clefairy.2bpp"
ChanseySprite::          INCBIN "gfx/sprites/chansey.2bpp"
SurfingPikachuSprite::   INCBIN "gfx/sprites/surfing_pikachu.2bpp"
JessieSprite::           INCBIN "gfx/sprites/jessie.2bpp"
JamesSprite::            INCBIN "gfx/sprites/james.2bpp"
BaldingGuySprite::       INCBIN "gfx/sprites/balding_guy.2bpp"
MewtwoSprite::           INCBIN "gfx/sprites/mewtwo.2bpp"
MewSprite::              INCBIN "gfx/sprites/mew.2bpp"
KrisSprite::             INCBIN "gfx/sprites/kris.2bpp"
JanineSprite::           INCBIN "gfx/sprites/janine.2bpp"
ArticunoSprite::         INCBIN "gfx/sprites/articuno.2bpp"
MoltresSprite::          INCBIN "gfx/sprites/moltres.2bpp"
ZapdosSprite::           INCBIN "gfx/sprites/zapdos.2bpp"
MrMimeSprite::           INCBIN "gfx/sprites/mr_mime.2bpp"
FlareonSprite::          INCBIN "gfx/sprites/flareon.2bpp"


SECTION "NPC Sprites 4", ROMX

BrockSprite::            INCBIN "gfx/sprites/brock.2bpp"
MistySprite::            INCBIN "gfx/sprites/misty.2bpp"
SurgeSprite::            INCBIN "gfx/sprites/surge.2bpp"
ErikaSprite::            INCBIN "gfx/sprites/erika.2bpp"
SabrinaSprite::          INCBIN "gfx/sprites/sabrina.2bpp"
BlaineSprite::           INCBIN "gfx/sprites/blaine.2bpp"
KabutoSprite::           INCBIN "gfx/sprites/kabuto.2bpp"
JolteonSprite::          INCBIN "gfx/sprites/jolteon.2bpp"


SECTION "NPC Sprites 5", ROMX

VaporeonSprite::         INCBIN "gfx/sprites/vaporeon.2bpp"
LaprasSprite::           INCBIN "gfx/sprites/lapras.2bpp"


SECTION "NPC Sprites 6", ROMX

PoliwrathSprite::        INCBIN "gfx/sprites/poliwrath.2bpp"
MeowthSprite::           INCBIN "gfx/sprites/meowth.2bpp"
CuboneSprite::           INCBIN "gfx/sprites/cubone.2bpp"
PsyduckSprite::          INCBIN "gfx/sprites/psyduck.2bpp"
NidoranmSprite::         INCBIN "gfx/sprites/nidoranm.2bpp"
NidorinoSprite::         INCBIN "gfx/sprites/nidorino.2bpp"
NidoranfSprite::         INCBIN "gfx/sprites/nidoranf.2bpp"
MachopSprite::           INCBIN "gfx/sprites/machop.2bpp"
MachokeSprite::          INCBIN "gfx/sprites/machoke.2bpp"
PidgeySprite::           INCBIN "gfx/sprites/pidgey.2bpp"
PidgeotSprite::          INCBIN "gfx/sprites/pidgeot.2bpp"
SpearowSprite::          INCBIN "gfx/sprites/spearow.2bpp"
FearowSprite::           INCBIN "gfx/sprites/fearow.2bpp"
Seel2Sprite::            INCBIN "gfx/sprites/seel2.2bpp"
SlowpokeSprite::         INCBIN "gfx/sprites/slowpoke.2bpp"
KangaskhanSprite::       INCBIN "gfx/sprites/kangaskhan.2bpp"
WigglytuffSprite::       INCBIN "gfx/sprites/wigglytuff.2bpp"


SECTION "Mon Icons 1", ROMX

MonIcons::
INCBIN "gfx/icons/null.2bpp"
INCBIN "gfx/icons/bulbasaur.2bpp"
INCBIN "gfx/icons/ivysaur.2bpp"
INCBIN "gfx/icons/venusaur.2bpp"
INCBIN "gfx/icons/charmander.2bpp"
INCBIN "gfx/icons/charmeleon.2bpp"
INCBIN "gfx/icons/charizard.2bpp"
INCBIN "gfx/icons/squirtle.2bpp"
INCBIN "gfx/icons/wartortle.2bpp"
INCBIN "gfx/icons/blastoise.2bpp"
INCBIN "gfx/icons/caterpie.2bpp"
INCBIN "gfx/icons/metapod.2bpp"
INCBIN "gfx/icons/butterfree.2bpp"
INCBIN "gfx/icons/weedle.2bpp"
INCBIN "gfx/icons/kakuna.2bpp"
INCBIN "gfx/icons/beedrill.2bpp"
INCBIN "gfx/icons/pidgey.2bpp"
INCBIN "gfx/icons/pidgeotto.2bpp"
INCBIN "gfx/icons/pidgeot.2bpp"
INCBIN "gfx/icons/rattata.2bpp"
INCBIN "gfx/icons/raticate.2bpp"
INCBIN "gfx/icons/spearow.2bpp"
INCBIN "gfx/icons/fearow.2bpp"
INCBIN "gfx/icons/ekans.2bpp"
INCBIN "gfx/icons/arbok.2bpp"
INCBIN "gfx/icons/pikachu.2bpp"
INCBIN "gfx/icons/raichu.2bpp"
INCBIN "gfx/icons/sandshrew.2bpp"
INCBIN "gfx/icons/sandslash.2bpp"
INCBIN "gfx/icons/nidoran_f.2bpp"
INCBIN "gfx/icons/nidorina.2bpp"
INCBIN "gfx/icons/nidoqueen.2bpp"
INCBIN "gfx/icons/nidoran_m.2bpp"
INCBIN "gfx/icons/nidorino.2bpp"
INCBIN "gfx/icons/nidoking.2bpp"
INCBIN "gfx/icons/clefairy.2bpp"
INCBIN "gfx/icons/clefable.2bpp"
INCBIN "gfx/icons/vulpix.2bpp"
INCBIN "gfx/icons/ninetales.2bpp"
INCBIN "gfx/icons/jigglypuff.2bpp"
INCBIN "gfx/icons/wigglytuff.2bpp"
INCBIN "gfx/icons/zubat.2bpp"
INCBIN "gfx/icons/golbat.2bpp"
INCBIN "gfx/icons/oddish.2bpp"
INCBIN "gfx/icons/gloom.2bpp"
INCBIN "gfx/icons/vileplume.2bpp"
INCBIN "gfx/icons/paras.2bpp"
INCBIN "gfx/icons/parasect.2bpp"
INCBIN "gfx/icons/venonat.2bpp"
INCBIN "gfx/icons/venomoth.2bpp"
INCBIN "gfx/icons/diglett.2bpp"
INCBIN "gfx/icons/dugtrio.2bpp"
INCBIN "gfx/icons/meowth.2bpp"
INCBIN "gfx/icons/persian.2bpp"
INCBIN "gfx/icons/psyduck.2bpp"
INCBIN "gfx/icons/golduck.2bpp"
INCBIN "gfx/icons/mankey.2bpp"
INCBIN "gfx/icons/primeape.2bpp"
INCBIN "gfx/icons/growlithe.2bpp"
INCBIN "gfx/icons/arcanine.2bpp"
INCBIN "gfx/icons/poliwag.2bpp"
INCBIN "gfx/icons/poliwhirl.2bpp"
INCBIN "gfx/icons/poliwrath.2bpp"
INCBIN "gfx/icons/abra.2bpp"
INCBIN "gfx/icons/kadabra.2bpp"
INCBIN "gfx/icons/alakazam.2bpp"
INCBIN "gfx/icons/machop.2bpp"
INCBIN "gfx/icons/machoke.2bpp"
INCBIN "gfx/icons/machamp.2bpp"
INCBIN "gfx/icons/bellsprout.2bpp"
INCBIN "gfx/icons/weepinbell.2bpp"
INCBIN "gfx/icons/victreebel.2bpp"
INCBIN "gfx/icons/tentacool.2bpp"
INCBIN "gfx/icons/tentacruel.2bpp"
INCBIN "gfx/icons/geodude.2bpp"
INCBIN "gfx/icons/graveler.2bpp"
INCBIN "gfx/icons/golem.2bpp"
INCBIN "gfx/icons/ponyta.2bpp"
INCBIN "gfx/icons/rapidash.2bpp"
INCBIN "gfx/icons/slowpoke.2bpp"
INCBIN "gfx/icons/slowbro.2bpp"
INCBIN "gfx/icons/magnemite.2bpp"
INCBIN "gfx/icons/magneton.2bpp"
INCBIN "gfx/icons/farfetchd.2bpp"
INCBIN "gfx/icons/doduo.2bpp"
INCBIN "gfx/icons/dodrio.2bpp"
INCBIN "gfx/icons/seel.2bpp"
INCBIN "gfx/icons/dewgong.2bpp"
INCBIN "gfx/icons/grimer.2bpp"
INCBIN "gfx/icons/muk.2bpp"
INCBIN "gfx/icons/shellder.2bpp"
INCBIN "gfx/icons/cloyster.2bpp"
INCBIN "gfx/icons/gastly.2bpp"
INCBIN "gfx/icons/haunter.2bpp"
INCBIN "gfx/icons/gengar.2bpp"
INCBIN "gfx/icons/onix.2bpp"
INCBIN "gfx/icons/drowzee.2bpp"
INCBIN "gfx/icons/hypno.2bpp"
INCBIN "gfx/icons/krabby.2bpp"
INCBIN "gfx/icons/kingler.2bpp"
INCBIN "gfx/icons/voltorb.2bpp"
INCBIN "gfx/icons/electrode.2bpp"
INCBIN "gfx/icons/exeggcute.2bpp"
INCBIN "gfx/icons/exeggutor.2bpp"
INCBIN "gfx/icons/cubone.2bpp"
INCBIN "gfx/icons/marowak.2bpp"
INCBIN "gfx/icons/hitmonlee.2bpp"
INCBIN "gfx/icons/hitmonchan.2bpp"
INCBIN "gfx/icons/lickitung.2bpp"
INCBIN "gfx/icons/koffing.2bpp"
INCBIN "gfx/icons/weezing.2bpp"
INCBIN "gfx/icons/rhyhorn.2bpp"
INCBIN "gfx/icons/rhydon.2bpp"
INCBIN "gfx/icons/chansey.2bpp"
INCBIN "gfx/icons/tangela.2bpp"
INCBIN "gfx/icons/kangaskhan.2bpp"
INCBIN "gfx/icons/horsea.2bpp"
INCBIN "gfx/icons/seadra.2bpp"
INCBIN "gfx/icons/goldeen.2bpp"
INCBIN "gfx/icons/seaking.2bpp"
INCBIN "gfx/icons/staryu.2bpp"
INCBIN "gfx/icons/starmie.2bpp"
INCBIN "gfx/icons/mr_mime.2bpp"
INCBIN "gfx/icons/scyther.2bpp"
INCBIN "gfx/icons/jynx.2bpp"
INCBIN "gfx/icons/electabuzz.2bpp"
INCBIN "gfx/icons/magmar.2bpp"
INCBIN "gfx/icons/pinsir.2bpp"


SECTION "Mon Icons 2", ROMX

MonIcons2::
INCBIN "gfx/icons/tauros.2bpp"
INCBIN "gfx/icons/magikarp.2bpp"
INCBIN "gfx/icons/gyarados.2bpp"
INCBIN "gfx/icons/lapras.2bpp"
INCBIN "gfx/icons/ditto.2bpp"
INCBIN "gfx/icons/eevee.2bpp"
INCBIN "gfx/icons/vaporeon.2bpp"
INCBIN "gfx/icons/jolteon.2bpp"
INCBIN "gfx/icons/flareon.2bpp"
INCBIN "gfx/icons/porygon.2bpp"
INCBIN "gfx/icons/omanyte.2bpp"
INCBIN "gfx/icons/omastar.2bpp"
INCBIN "gfx/icons/kabuto.2bpp"
INCBIN "gfx/icons/kabutops.2bpp"
INCBIN "gfx/icons/aerodactyl.2bpp"
INCBIN "gfx/icons/snorlax.2bpp"
INCBIN "gfx/icons/articuno.2bpp"
INCBIN "gfx/icons/zapdos.2bpp"
INCBIN "gfx/icons/moltres.2bpp"
INCBIN "gfx/icons/dratini.2bpp"
INCBIN "gfx/icons/dragonair.2bpp"
INCBIN "gfx/icons/dragonite.2bpp"
INCBIN "gfx/icons/mewtwo.2bpp"
INCBIN "gfx/icons/mew.2bpp"
